-- Lisää DROP TABLE lauseet tähän tiedostoon
DROP TABLE IF EXISTS hospitals CASCADE;
DROP TABLE IF EXISTS roles CASCADE;
DROP TABLE IF EXISTS importances CASCADE;
DROP TABLE IF EXISTS hours CASCADE;
DROP TABLE IF EXISTS importance_role CASCADE;
DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS hour_users CASCADE;
DROP TABLE IF EXISTS hospital_users CASCADE;